# Setup
title: Robot & Chisel
tagline: stuff by michael ferguson. robots, woodworking, etc.
url: https://robotandchisel.github.io
paginate: 3
paginate_path: "/blog/page:num/"
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options
highlighter: rouge

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-RD4LZXXWMR

# Specify the author for blog posts
author:
  name: Michael Ferguson
  url: https://twitter.com/therealfergs
